version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Execute Sample Project
          command: |
            mkdir build
            cd build
            cmake ..
            make
            cd test
            chmod +x ./CatchSampleExampleTest
            ./CatchSampleExampleTest
            
workflows:
  version: 2
  build:
    jobs:
      - build
